{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"SAC\",\"JR\",\"FS\",\"AC\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "AutoDetected_28cb9c10-815c-4cde-9846-f9fae58ccb74",
        "fromColumn": "ACT ID",
        "fromTable": "JR",
        "isActive": false,
        "toColumn": "ACT ID",
        "toTable": "AC"
      },
      {
        "name": "AutoDetected_181d66b9-548e-49dc-83e2-aeaa7730f6c2",
        "fromColumn": "SA ID",
        "fromTable": "JR",
        "isActive": false,
        "toColumn": "SA ID",
        "toTable": "SAC"
      },
      {
        "name": "AutoDetected_23ae05ae-a759-4e3b-9be4-60237ca0190f",
        "fromColumn": "FS ID",
        "fromTable": "JR",
        "isActive": false,
        "toColumn": "FS ID",
        "toTable": "FS"
      },
      {
        "name": "6f0caf64-59f7-4ccf-8476-b9553faea6ef",
        "fromColumn": "Date",
        "fromTable": "Calender Amlan",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_fffb432f-616a-4d3f-8023-d865878d3795"
      },
      {
        "name": "3525a65b-3c3d-1938-ac40-89e5c1242e54",
        "fromColumn": "Date",
        "fromTable": "JR",
        "toColumn": "Date",
        "toTable": "Calender Amlan"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_8ed80194-b6af-4d9e-aea3-168b294007bc",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "27568a21-3a7f-49c6-92bd-135c40ed096b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "13401607-e72b-4c7c-a4b4-283fee2959e7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "a2f310ab-4693-4daa-bd47-c755df0383d1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0b897692-7116-4e8d-85ee-73072e2c725a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "765516c8-4a36-4363-9446-8ffd16b7e6f5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "8fa0dc19-07c3-4d2e-b35f-d18c7a614400",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "70ab9782-4bbe-40bd-baa9-c056868b46e5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "073b9e4f-ead9-4bf7-a22b-b42bd6a47624",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "688d3801-70f1-4197-82a0-b1de17835642",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6c2454a3-3cd7-4571-b033-c92c8d4638ea",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b3412ee7-d2ed-445a-97fe-1419c99922ec",
                "ordinal": 3
              }
            ],
            "lineageTag": "6041a11d-3c73-409b-af2e-bc7977830e8d"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "2d06b31a-9ddb-4580-9333-a73b9dacbe16",
        "partitions": [
          {
            "name": "DateTableTemplate_8ed80194-b6af-4d9e-aea3-168b294007bc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Amlan Measure",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a28ced9fe5584483b4fb40b9d17da897"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b22948df-5dce-425f-8a89-be5242635758",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "12f7527c-2749-4318-9a01-9d94c1881cea",
        "measures": [
          {
            "name": "Total Balance",
            "expression": "SUM(JR[Balance])",
            "formatString": "0",
            "lineageTag": "a061e28a-8d09-46e6-b554-334eba1f0d6d"
          },
          {
            "name": "Total Revenue",
            "expression": "CALCULATE(SUM(JR[Balance]),FILTER(JR,JR[Account Categories]=\"Revenue\"))",
            "formatString": "0",
            "lineageTag": "889bcdbe-dab2-43b0-bde4-d1ec407c2285"
          },
          {
            "name": "Total Expense",
            "expression": "CALCULATE(SUM(JR[Balance]),FILTER(JR,JR[Account Categories]=\"Expense\"))",
            "formatString": "0",
            "lineageTag": "ee985a27-9c1f-4555-83a6-12cdbc656526"
          },
          {
            "name": "Net Profit",
            "expression": "[Total Revenue] - [Total Expense]",
            "formatString": "0.00",
            "lineageTag": "5b2e25d3-ce6a-4e26-a47a-ef1db72ed66b"
          },
          {
            "name": "Profit Loss Variance",
            "expression": [
              "",
              "VAR Uparrow = UNICHAR(129137)",
              "VAR Downarrow = UNICHAR(129139)",
              "",
              "RETURN",
              "    IF([Net Profit] > 0,Uparrow,Downarrow)",
              ""
            ],
            "lineageTag": "70ca83ac-a616-46ae-bfdd-df9b93d8bd3f"
          },
          {
            "name": "Current Y",
            "expression": [
              "CALCULATE(SUM(JR[Balance]),",
              "MONTH('Calender Amlan'[Month]) = MONTH(TODAY()),",
              "Year('Calender Amlan'[Month]) = Year(TODAY()))"
            ],
            "formatString": "0",
            "lineageTag": "fb83015a-86f7-45f2-a3a5-72b25efd6002"
          },
          {
            "name": "Previous Y",
            "expression": [
              "CALCULATE(SUM(JR[Balance]),",
              "MONTH('Calender Amlan'[Month]) = MONTH(TODAY())-1,",
              "Year('Calender Amlan'[Month]) = Year(TODAY()))"
            ],
            "formatString": "0",
            "lineageTag": "49b0ff40-b209-4aaa-90c0-6b1b527bafe4"
          },
          {
            "name": "Profit %",
            "expression": "[Net Profit] / [Total Revenue]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0063cecf-3218-4f53-8224-3c96577d5515"
          }
        ],
        "partitions": [
          {
            "name": "Amlan Measure",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "SAC",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Sub Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "473f1a23-5c38-4da9-abab-9fc6080a59ac",
            "sourceColumn": "Sub Account",
            "summarizeBy": "none"
          },
          {
            "name": "SA ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04d05a0d-dd2b-4384-a5ad-d5e869f2a95f",
            "sourceColumn": "SA ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6a314796-567e-4848-988d-f0c6b01c909f",
        "partitions": [
          {
            "name": "SAC",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\" https://drive.google.com/uc?export=download&id=1Aq8j52GBzqpjmTRtZdKTkQnbRZF9R_E8\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Sub Account\", type text}, {\"SA ID\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "JR",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Journal ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97be3e8d-d03a-4990-bc27-a183b2b04357",
            "sourceColumn": "Journal ID",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "edb08008-2afc-4456-85f0-a9da589ca34c",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Account ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a9158b2-dbf6-4254-a147-595cb2190c49",
            "sourceColumn": "Account ID",
            "summarizeBy": "none"
          },
          {
            "name": "Dr Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "d9ea5e26-8596-4398-b053-63153f92a9bd",
            "sourceColumn": "Dr Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Cr Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "89ddc322-e4b7-450d-8292-6a9224fb6dcf",
            "sourceColumn": "Cr Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Details",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8800e602-1273-4bbc-8d8e-2a4e0ef2e347",
            "sourceColumn": "Details",
            "summarizeBy": "none"
          },
          {
            "name": "Cash flow statement operator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50391b48-930b-4cee-b820-afcac84c8530",
            "sourceColumn": "Cash flow statement operator",
            "summarizeBy": "none"
          },
          {
            "name": "Cash flow Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6aa9be88-6c1f-414e-9f33-886c2cd08ce2",
            "sourceColumn": "Cash flow Status",
            "summarizeBy": "none"
          },
          {
            "name": "Cash flow Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "74f957f6-3650-4d0e-81e7-dc158d034d9f",
            "sourceColumn": "Cash flow Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "ACT ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7aa8e0c-7001-444d-a4bc-6dd040e76690",
            "sourceColumn": "ACT ID",
            "summarizeBy": "none"
          },
          {
            "name": "SA ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e75e1c5-d556-4271-a468-0143f8554408",
            "sourceColumn": "SA ID",
            "summarizeBy": "none"
          },
          {
            "name": "FS ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e685e6e9-7fb2-467f-b5c9-f581a1f081bc",
            "sourceColumn": "FS ID",
            "summarizeBy": "none"
          },
          {
            "name": "Account Categories",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2f83890-861f-4ca3-907e-b12d5950bbc6",
            "sourceColumn": "Account Categories",
            "summarizeBy": "none"
          },
          {
            "name": "Sub Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cfa6264b-4232-42f4-83f6-2998031248f8",
            "sourceColumn": "Sub Account",
            "summarizeBy": "none"
          },
          {
            "name": "Financial Statements",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5278b739-b2c4-4ccf-bd1f-7c90a42c5118",
            "sourceColumn": "Financial Statements",
            "summarizeBy": "none"
          },
          {
            "name": "Account Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd1229a9-debc-428a-8fb9-9521627f37a2",
            "sourceColumn": "Account Name",
            "summarizeBy": "none"
          },
          {
            "name": "Net Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "f2543210-2594-4977-971f-a845dcc6489b",
            "sourceColumn": "Net Balance",
            "summarizeBy": "sum"
          },
          {
            "name": "Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "21c99497-06a2-46b8-a2f0-6ef1478c5248",
            "sourceColumn": "Balance",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "abd19040-da3a-4b83-ab99-b0c329457115",
        "partitions": [
          {
            "name": "JR",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1muzBTVjMEq2UeiAlJJaukjfNBAGYfCFB\"),[Delimiter=\",\", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Journal ID\", type text}, {\"Date\", type date}, {\"Account Name\", type text}, {\"Account ID\", type text}, {\"Dr Amount\", Int64.Type}, {\"Cr Amount\", Int64.Type}, {\"Details\", type text}, {\"Cash flow statement operator\", type text}, {\"Cash flow Status\", type text}, {\"Cash flow Amount\", Int64.Type}, {\"ACT ID\", type text}, {\"SA ID\", type text}, {\"FS ID\", type text}, {\"Account Categories\", type text}, {\"Sub Account\", type text}, {\"Financial Statements\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",null,0,Replacer.ReplaceValue,{\"Journal ID\", \"Dr Amount\", \"Cr Amount\", \"Cash flow Amount\"}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Replaced Value\", \"New\", each if [Account Name] = \"Cash at bank\" then \"Cash at Bank\" else if [Account Name] = \"Utility expense\" then \"Utility Expense\" else null),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Conditional Column\",{\"Journal ID\", \"Date\", \"Account Name\", \"New\", \"Account ID\", \"Dr Amount\", \"Cr Amount\", \"Details\", \"Cash flow statement operator\", \"Cash flow Status\", \"Cash flow Amount\", \"ACT ID\", \"SA ID\", \"FS ID\", \"Account Categories\", \"Sub Account\", \"Financial Statements\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns\",{\"New\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Removed Columns\", \"New\", each if [Account Name] = \"Cash at bank\" then \"Cash at Bank\" else",
                "if [Account Name] = \"Utility expense\" then \"Utility Expense\" else [Account Name]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Custom\",{{\"Account Name\", \"Account Name 2\"}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Renamed Columns\",{\"Account Name 2\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"New\", \"Account Name\"}}),",
                "    #\"Inserted Subtraction\" = Table.AddColumn(#\"Renamed Columns1\", \"Subtraction\", each [Dr Amount] - [Cr Amount], type number),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Inserted Subtraction\",{{\"Subtraction\", \"Net Balance\"}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Renamed Columns2\", \"Balance\", each if [Net Balance] < 0 then [Net Balance] *-1 else ",
                "[Net Balance]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"Balance\", Int64.Type}, {\"Net Balance\", Int64.Type}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Financial Statements",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7965ca3c-bf02-4ebc-9254-34bde914ee92",
            "sourceColumn": "Financial Statements",
            "summarizeBy": "none"
          },
          {
            "name": "FS ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b9ce341-3f1e-4810-9628-2154a928bf5d",
            "sourceColumn": "FS ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f88f0929-8074-479b-b77f-8929649fb6e2",
        "partitions": [
          {
            "name": "FS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1Jt_zDhxd6l5jsXbtHF3mrwiqjpDtLl8M\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Financial Statements\", type text}, {\"FS ID\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "AC",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Account Categories",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adca4cf3-7f35-4a49-b443-f0328e603d52",
            "sourceColumn": "Account Categories",
            "summarizeBy": "none"
          },
          {
            "name": "ACT ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02e35365-57ba-424b-8ef4-88d7e625744e",
            "sourceColumn": "ACT ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8251ad68-695e-49a5-9505-b7717c6c5a08",
        "partitions": [
          {
            "name": "AC",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1A3Q8n4q8aFdxMavB4gum-sb65yEuWE3u\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Account Categories\", type text}, {\"ACT ID\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calender Amlan",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f366a225a6e24111bb43e47e8b2d9679"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "162a01c6-57ba-4304-8f53-3c7639f211f8",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_fffb432f-616a-4d3f-8023-d865878d3795"
                },
                "isDefault": true,
                "relationship": "6f0caf64-59f7-4ccf-8476-b9553faea6ef"
              }
            ]
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "FORMAT('Calender Amlan'[Date],\"MM\")",
            "formatString": "0",
            "lineageTag": "86ca8217-d162-4de0-84c2-dfe162ac2cdf",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "FORMAT('Calender Amlan'[Date],\"YYYY\")",
            "formatString": "0",
            "lineageTag": "c0e1b1b0-766f-4f55-8f4f-1b7750f03499",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "497aed6c-7065-47a3-8157-29716497dd02",
        "partitions": [
          {
            "name": "Calender Amlan",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(MIN(JR[Date]),MAX(JR[Date]))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_fffb432f-616a-4d3f-8023-d865878d3795",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d5c561d6-6e15-4246-afc6-9cbaa499a4ef",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "385058a6-d3d9-439d-b42c-f7431c463d30",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "790072bf-9340-4ee2-ba8a-a27ee853e445",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8337c876-a11c-431d-90a7-abee2a6413fb",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "7269671f-b372-42f1-a865-c24bcaa8b3c7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "3728cc2a-e862-4413-9b43-8c7372276383",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "735120b1-fb80-41e6-8d62-d43970a3f7b6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5965a636-133f-427b-9a49-a2ef53a1c095",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f2a0fb71-0499-4543-8fa9-b4137907f5f9",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "bd653f58-d6e5-4c30-96ea-c07c5b1826a3",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "8d783931-b84d-4395-b01e-94327fc33ad5",
                "ordinal": 3
              }
            ],
            "lineageTag": "1fdc4650-df07-4eeb-8b01-a16f5dfd67bb"
          }
        ],
        "isHidden": true,
        "lineageTag": "19524faf-7514-4ef9-b94e-0cf669a8f0bd",
        "partitions": [
          {
            "name": "LocalDateTable_fffb432f-616a-4d3f-8023-d865878d3795",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calender Amlan'[Date])), 1, 1), Date(Year(MAX('Calender Amlan'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Amlan Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ead96bc2bbc24ab59f9e25c4def4cde4"
          }
        ],
        "columns": [
          {
            "name": "Amlan Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "58718cb6-4e84-4b98-a1b6-633d63228cf0",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Amlan Parameter Fields"
                }
              ]
            },
            "sortByColumn": "Amlan Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Amlan Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "f8eb13d3-c979-44fa-bafc-3a1c23dca2fc",
            "sortByColumn": "Amlan Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Amlan Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "ea0fcfd9-b2f1-4ba8-8124-328b876487e9",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "ec787141-1701-49ff-a9e0-7026b180fc58",
        "partitions": [
          {
            "name": "Amlan Parameter",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Total Expense\", NAMEOF('Amlan Measure'[Total Expense]), 0),",
                "    (\"Total Revenue\", NAMEOF('Amlan Measure'[Total Revenue]), 1),",
                "    (\"Profit %\", NAMEOF('Amlan Measure'[Profit %]), 2)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}