{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"SAC\",\"JR\",\"FS\",\"AC\",\"TB\",\"JR (2)\",\"TB 2\",\"Merge1\",\"Merge2\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.908.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Merge1",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Table.NestedJoin(#\"TB 2\", {\"Financial Statements\"}, FS, {\"Financial Statements\"}, \"FS\", JoinKind.LeftOuter),\r",
          "    #\"Expanded FS\" = Table.ExpandTableColumn(Source, \"FS\", {\"FS ID\"}, {\"FS ID\"})\r",
          "in\r",
          "    #\"Expanded FS\""
        ],
        "kind": "m",
        "lineageTag": "637e800f-0f7b-41f0-ad43-6f9d42b0aa41"
      },
      {
        "name": "Merge2",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Table.NestedJoin(Merge1, {\"Account Categories\"}, AC, {\"Account Categories\"}, \"AC\", JoinKind.LeftOuter),\r",
          "    #\"Expanded AC\" = Table.ExpandTableColumn(Source, \"AC\", {\"ACT ID\"}, {\"ACT ID\"})\r",
          "in\r",
          "    #\"Expanded AC\""
        ],
        "kind": "m",
        "lineageTag": "3ee980aa-550a-4cf0-bbf1-dae5bafb25a9"
      },
      {
        "name": "JR (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1muzBTVjMEq2UeiAlJJaukjfNBAGYfCFB\"),[Delimiter=\",\", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.None]),\r",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),\r",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Journal ID\", type text}, {\"Date\", type date}, {\"Account Name\", type text}, {\"Account ID\", type text}, {\"Dr Amount\", Int64.Type}, {\"Cr Amount\", Int64.Type}, {\"Details\", type text}, {\"Cash flow statement operator\", type text}, {\"Cash flow Status\", type text}, {\"Cash flow Amount\", Int64.Type}, {\"ACT ID\", type text}, {\"SA ID\", type text}, {\"FS ID\", type text}, {\"Account Categories\", type text}, {\"Sub Account\", type text}, {\"Financial Statements\", type text}}),\r",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",null,0,Replacer.ReplaceValue,{\"Journal ID\", \"Dr Amount\", \"Cr Amount\", \"Cash flow Amount\"}),\r",
          "    #\"Added Conditional Column\" = Table.AddColumn(#\"Replaced Value\", \"New\", each if [Account Name] = \"Cash at bank\" then \"Cash at Bank\" else if [Account Name] = \"Utility expense\" then \"Utility Expense\" else null),\r",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Conditional Column\",{\"Journal ID\", \"Date\", \"Account Name\", \"New\", \"Account ID\", \"Dr Amount\", \"Cr Amount\", \"Details\", \"Cash flow statement operator\", \"Cash flow Status\", \"Cash flow Amount\", \"ACT ID\", \"SA ID\", \"FS ID\", \"Account Categories\", \"Sub Account\", \"Financial Statements\"}),\r",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns\",{\"New\"}),\r",
          "    #\"Added Custom\" = Table.AddColumn(#\"Removed Columns\", \"New\", each if [Account Name] = \"Cash at bank\" then \"Cash at Bank\" else\r",
          "if [Account Name] = \"Utility expense\" then \"Utility Expense\" else [Account Name]),\r",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Custom\",{{\"Account Name\", \"Account Name 2\"}, {\"New\", \"Account Name\"}}),\r",
          "    #\"Grouped Rows\" = Table.Group(#\"Renamed Columns\", {\"Account Name\"}, {{\"DR Amount\", each List.Sum([Dr Amount]), type nullable number}, {\"CR Amount\", each List.Sum([Cr Amount]), type nullable number}})\r",
          "in\r",
          "    #\"Grouped Rows\""
        ],
        "kind": "m",
        "lineageTag": "f0727411-d5bd-48b1-96e5-ff572e3fb321"
      },
      {
        "name": "TB 2",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Table.NestedJoin(#\"JR (2)\", {\"Account Name\"}, JR, {\"New\"}, \"JR\", JoinKind.LeftOuter),\r",
          "    #\"Expanded JR\" = Table.ExpandTableColumn(Source, \"JR\", {\"ACT ID\", \"SA ID\", \"FS ID\", \"Account Categories\", \"Sub Account\", \"Financial Statements\"}, {\"ACT ID\", \"SA ID\", \"FS ID\", \"Account Categories\", \"Sub Account\", \"Financial Statements\"}),\r",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded JR\",{\"ACT ID\", \"SA ID\", \"FS ID\"}),\r",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns\", {\"Account Name\"}),\r",
          "    #\"Merged Queries\" = Table.NestedJoin(#\"Removed Duplicates\", {\"Sub Account\"}, SAC, {\"Sub Account\"}, \"SAC\", JoinKind.LeftOuter),\r",
          "    #\"Expanded SAC\" = Table.ExpandTableColumn(#\"Merged Queries\", \"SAC\", {\"SA ID\"}, {\"SA ID\"})\r",
          "in\r",
          "    #\"Expanded SAC\""
        ],
        "kind": "m",
        "lineageTag": "75ad2319-25eb-4803-a656-25bf86f1d552"
      }
    ],
    "relationships": [
      {
        "name": "95d52218-dc9e-4419-99e1-4011efa95e5a",
        "fromColumn": "Date",
        "fromTable": "JR",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3d3b930c-7a82-4a65-a014-fde4d70efecc"
      },
      {
        "name": "AutoDetected_28cb9c10-815c-4cde-9846-f9fae58ccb74",
        "fromColumn": "ACT ID",
        "fromTable": "JR",
        "isActive": false,
        "toColumn": "ACT ID",
        "toTable": "AC"
      },
      {
        "name": "AutoDetected_181d66b9-548e-49dc-83e2-aeaa7730f6c2",
        "fromColumn": "SA ID",
        "fromTable": "JR",
        "isActive": false,
        "toColumn": "SA ID",
        "toTable": "SAC"
      },
      {
        "name": "AutoDetected_23ae05ae-a759-4e3b-9be4-60237ca0190f",
        "fromColumn": "FS ID",
        "fromTable": "JR",
        "isActive": false,
        "toColumn": "FS ID",
        "toTable": "FS"
      },
      {
        "name": "AutoDetected_85c5390e-cdd8-47da-8459-c4b868819abf",
        "fromColumn": "Sub Account",
        "fromTable": "TB",
        "toColumn": "Sub Account",
        "toTable": "SAC"
      },
      {
        "name": "AutoDetected_a1f11b57-8831-47e6-8504-d3f31ba957c8",
        "fromColumn": "Account Name 2",
        "fromTable": "JR",
        "toColumn": "Account Name",
        "toTable": "TB"
      },
      {
        "name": "AutoDetected_a1308472-1186-4c55-9b02-7e4821eadf0e",
        "fromColumn": "ACT ID",
        "fromTable": "TB",
        "toColumn": "ACT ID",
        "toTable": "AC"
      },
      {
        "name": "AutoDetected_86eb6d21-7770-432f-a7bc-c4048b27544a",
        "fromColumn": "FS ID",
        "fromTable": "TB",
        "toColumn": "FS ID",
        "toTable": "FS"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_8ed80194-b6af-4d9e-aea3-168b294007bc",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "27568a21-3a7f-49c6-92bd-135c40ed096b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "13401607-e72b-4c7c-a4b4-283fee2959e7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "a2f310ab-4693-4daa-bd47-c755df0383d1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0b897692-7116-4e8d-85ee-73072e2c725a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "765516c8-4a36-4363-9446-8ffd16b7e6f5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "8fa0dc19-07c3-4d2e-b35f-d18c7a614400",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "70ab9782-4bbe-40bd-baa9-c056868b46e5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "073b9e4f-ead9-4bf7-a22b-b42bd6a47624",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "688d3801-70f1-4197-82a0-b1de17835642",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6c2454a3-3cd7-4571-b033-c92c8d4638ea",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b3412ee7-d2ed-445a-97fe-1419c99922ec",
                "ordinal": 3
              }
            ],
            "lineageTag": "6041a11d-3c73-409b-af2e-bc7977830e8d"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "2d06b31a-9ddb-4580-9333-a73b9dacbe16",
        "partitions": [
          {
            "name": "DateTableTemplate_8ed80194-b6af-4d9e-aea3-168b294007bc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Amlan Measure",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a28ced9fe5584483b4fb40b9d17da897"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b22948df-5dce-425f-8a89-be5242635758",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "12f7527c-2749-4318-9a01-9d94c1881cea",
        "measures": [
          {
            "name": "Revenue",
            "expression": "CALCULATE(SUM(JR[Balance]),FILTER(JR,JR[Account Categories]=\"Revenue\"))",
            "formatString": "0",
            "lineageTag": "1aacad08-cf7c-44fe-b1a5-030b850b2861"
          },
          {
            "name": "Expense",
            "expression": "CALCULATE(SUM(JR[Balance]),FILTER(JR,JR[Account Categories]=\"Expense\"))",
            "formatString": "0",
            "lineageTag": "73b311c2-4708-4122-8075-32a423916799"
          },
          {
            "name": "Net Profit",
            "expression": "[Revenue] - [Expense]",
            "formatString": "0.00",
            "lineageTag": "2f087605-2ea0-4eba-89e3-3607132bb17f"
          },
          {
            "name": "Profit %",
            "expression": "[Net Profit] / [Revenue]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d7332e02-f835-4cd2-a843-64f73fa3a704"
          },
          {
            "name": "Current Y",
            "expression": [
              "CALCULATE(SUM(JR[Balance]),",
              "                MONTH(JR[Balance]= MONTH(TODAY())),",
              "                YEAR(JR[Balance]= YEAR(TODAY())))"
            ],
            "formatString": "0",
            "lineageTag": "713c04c4-0c43-4fb5-a91e-a8265b62edbd"
          },
          {
            "name": "Previous Y",
            "expression": [
              "CALCULATE(SUM(JR[Balance]),",
              "                MONTH(JR[Balance]= MONTH(TODAY()))-1,",
              "                YEAR(JR[Balance]= YEAR(TODAY())))-1"
            ],
            "formatString": "0",
            "lineageTag": "dfbb2c10-9730-459a-aa37-936cf2831260"
          },
          {
            "name": "Variance",
            "expression": "([Current Y] - [Previous Y])",
            "formatString": "0",
            "lineageTag": "bc9db6ec-41fc-40bc-b385-b6ee83934081"
          }
        ],
        "partitions": [
          {
            "name": "Amlan Measure",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "SAC",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Sub Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "473f1a23-5c38-4da9-abab-9fc6080a59ac",
            "sourceColumn": "Sub Account",
            "summarizeBy": "none"
          },
          {
            "name": "SA ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04d05a0d-dd2b-4384-a5ad-d5e869f2a95f",
            "sourceColumn": "SA ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6a314796-567e-4848-988d-f0c6b01c909f",
        "partitions": [
          {
            "name": "SAC",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\" https://drive.google.com/uc?export=download&id=1Aq8j52GBzqpjmTRtZdKTkQnbRZF9R_E8\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Sub Account\", type text}, {\"SA ID\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "JR",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Journal ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97be3e8d-d03a-4990-bc27-a183b2b04357",
            "sourceColumn": "Journal ID",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "edb08008-2afc-4456-85f0-a9da589ca34c",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_3d3b930c-7a82-4a65-a014-fde4d70efecc"
                },
                "isDefault": true,
                "relationship": "95d52218-dc9e-4419-99e1-4011efa95e5a"
              }
            ]
          },
          {
            "name": "Account Name 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f6e4c954-081b-479f-989e-5392019ad93c",
            "sourceColumn": "Account Name 2",
            "summarizeBy": "none"
          },
          {
            "name": "Account ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a9158b2-dbf6-4254-a147-595cb2190c49",
            "sourceColumn": "Account ID",
            "summarizeBy": "none"
          },
          {
            "name": "Dr Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "d9ea5e26-8596-4398-b053-63153f92a9bd",
            "sourceColumn": "Dr Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Cr Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "89ddc322-e4b7-450d-8292-6a9224fb6dcf",
            "sourceColumn": "Cr Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Details",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8800e602-1273-4bbc-8d8e-2a4e0ef2e347",
            "sourceColumn": "Details",
            "summarizeBy": "none"
          },
          {
            "name": "Cash flow statement operator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50391b48-930b-4cee-b820-afcac84c8530",
            "sourceColumn": "Cash flow statement operator",
            "summarizeBy": "none"
          },
          {
            "name": "Cash flow Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6aa9be88-6c1f-414e-9f33-886c2cd08ce2",
            "sourceColumn": "Cash flow Status",
            "summarizeBy": "none"
          },
          {
            "name": "Cash flow Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "74f957f6-3650-4d0e-81e7-dc158d034d9f",
            "sourceColumn": "Cash flow Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "ACT ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7aa8e0c-7001-444d-a4bc-6dd040e76690",
            "sourceColumn": "ACT ID",
            "summarizeBy": "none"
          },
          {
            "name": "SA ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e75e1c5-d556-4271-a468-0143f8554408",
            "sourceColumn": "SA ID",
            "summarizeBy": "none"
          },
          {
            "name": "FS ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e685e6e9-7fb2-467f-b5c9-f581a1f081bc",
            "sourceColumn": "FS ID",
            "summarizeBy": "none"
          },
          {
            "name": "Account Categories",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2f83890-861f-4ca3-907e-b12d5950bbc6",
            "sourceColumn": "Account Categories",
            "summarizeBy": "none"
          },
          {
            "name": "Sub Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cfa6264b-4232-42f4-83f6-2998031248f8",
            "sourceColumn": "Sub Account",
            "summarizeBy": "none"
          },
          {
            "name": "Financial Statements",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5278b739-b2c4-4ccf-bd1f-7c90a42c5118",
            "sourceColumn": "Financial Statements",
            "summarizeBy": "none"
          },
          {
            "name": "Account Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd1229a9-debc-428a-8fb9-9521627f37a2",
            "sourceColumn": "Account Name",
            "summarizeBy": "none"
          },
          {
            "name": "Net Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2eb713a5-4e94-4c6e-8180-4aea53748770",
            "sourceColumn": "Net Balance",
            "summarizeBy": "sum"
          },
          {
            "name": "Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "36b5bec7-a2b0-4692-b863-4ba3bfe2257d",
            "sourceColumn": "Balance",
            "summarizeBy": "sum"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH(JR[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "7dd3ed03-b093-4f11-87aa-7e22bd88920a",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Yaer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR(JR[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "6b826328-431d-42f7-8e91-b155a7725407",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "abd19040-da3a-4b83-ab99-b0c329457115",
        "partitions": [
          {
            "name": "JR",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1muzBTVjMEq2UeiAlJJaukjfNBAGYfCFB\"),[Delimiter=\",\", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Journal ID\", type text}, {\"Date\", type date}, {\"Account Name\", type text}, {\"Account ID\", type text}, {\"Dr Amount\", Int64.Type}, {\"Cr Amount\", Int64.Type}, {\"Details\", type text}, {\"Cash flow statement operator\", type text}, {\"Cash flow Status\", type text}, {\"Cash flow Amount\", Int64.Type}, {\"ACT ID\", type text}, {\"SA ID\", type text}, {\"FS ID\", type text}, {\"Account Categories\", type text}, {\"Sub Account\", type text}, {\"Financial Statements\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",null,0,Replacer.ReplaceValue,{\"Journal ID\", \"Dr Amount\", \"Cr Amount\", \"Cash flow Amount\"}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Replaced Value\", \"New\", each if [Account Name] = \"Cash at bank\" then \"Cash at Bank\" else if [Account Name] = \"Utility expense\" then \"Utility Expense\" else null),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Conditional Column\",{\"Journal ID\", \"Date\", \"Account Name\", \"New\", \"Account ID\", \"Dr Amount\", \"Cr Amount\", \"Details\", \"Cash flow statement operator\", \"Cash flow Status\", \"Cash flow Amount\", \"ACT ID\", \"SA ID\", \"FS ID\", \"Account Categories\", \"Sub Account\", \"Financial Statements\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns\",{\"New\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Removed Columns\", \"New\", each if [Account Name] = \"Cash at bank\" then \"Cash at Bank\" else",
                "if [Account Name] = \"Utility expense\" then \"Utility Expense\" else [Account Name]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Custom\",{{\"Account Name\", \"Account Name 2\"}, {\"New\", \"New\"}}),",
                "    #\"Inserted Subtraction\" = Table.AddColumn(#\"Renamed Columns\", \"Subtraction\", each [Dr Amount] - [Cr Amount], type number),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Inserted Subtraction\",{\"Journal ID\", \"Date\", \"Account Name 2\", \"Account ID\", \"Dr Amount\", \"Cr Amount\", \"Subtraction\", \"Details\", \"Cash flow statement operator\", \"Cash flow Status\", \"Cash flow Amount\", \"ACT ID\", \"SA ID\", \"FS ID\", \"Account Categories\", \"Sub Account\", \"Financial Statements\", \"New\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Reordered Columns1\",{{\"Subtraction\", \"Net Balance\"}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Renamed Columns1\", \"Balance\", each if [Net Balance] < 0 then [Net Balance]*-1 else ",
                "[Net Balance]),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Custom1\",{{\"New\", \"Account Name\"}})",
                "in",
                "    #\"Renamed Columns2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_3d3b930c-7a82-4a65-a014-fde4d70efecc",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e4c51675-2b17-4f27-bff5-4f6a94bdfe0f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "0e2777d2-a44d-4fab-83cd-79debb23d40c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "304a0212-3d6a-4aba-b087-ce9b740530c0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ec1ea5fb-b5c0-4e84-8c31-0653f79cf667",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "88fb11e6-4546-489b-9326-68e239b4a1c7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "34102e60-b361-48d3-a43f-0a28fdbfb4ae",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "026b2e7d-d7d0-4178-a9a9-50bfc252fd80",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "3dbcdbb8-c2e4-4dd8-b312-c3d744eb3196",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d5024f57-30ed-41db-94d4-c5d5407d9ebb",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3eba56d7-56ad-473d-a8c5-92c633da5a9a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c046dd23-333a-4c84-900b-45e9690780cc",
                "ordinal": 3
              }
            ],
            "lineageTag": "96821070-e2d4-44a0-b7da-4b03950c72ef"
          }
        ],
        "isHidden": true,
        "lineageTag": "16c986bb-ef79-4396-b4cf-309f5a7062ea",
        "partitions": [
          {
            "name": "LocalDateTable_3d3b930c-7a82-4a65-a014-fde4d70efecc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('JR'[Date])), 1, 1), Date(Year(MAX('JR'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "FS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Financial Statements",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7965ca3c-bf02-4ebc-9254-34bde914ee92",
            "sourceColumn": "Financial Statements",
            "summarizeBy": "none"
          },
          {
            "name": "FS ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b9ce341-3f1e-4810-9628-2154a928bf5d",
            "sourceColumn": "FS ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f88f0929-8074-479b-b77f-8929649fb6e2",
        "partitions": [
          {
            "name": "FS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1Jt_zDhxd6l5jsXbtHF3mrwiqjpDtLl8M\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Financial Statements\", type text}, {\"FS ID\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "AC",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Account Categories",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adca4cf3-7f35-4a49-b443-f0328e603d52",
            "sourceColumn": "Account Categories",
            "summarizeBy": "none"
          },
          {
            "name": "ACT ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02e35365-57ba-424b-8ef4-88d7e625744e",
            "sourceColumn": "ACT ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8251ad68-695e-49a5-9505-b7717c6c5a08",
        "partitions": [
          {
            "name": "AC",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1A3Q8n4q8aFdxMavB4gum-sb65yEuWE3u\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Account Categories\", type text}, {\"ACT ID\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TB",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Account ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28b392fb-003a-4f29-a07a-c6355ac0f92f",
            "sourceColumn": "Account ID",
            "summarizeBy": "none"
          },
          {
            "name": "Account Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "91c0da7a-2e22-4c63-9b0c-5245f5353ee4",
            "sourceColumn": "Account Name",
            "summarizeBy": "none"
          },
          {
            "name": "Dr Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27f0d4af-0100-46b1-9e57-ad310286c405",
            "sourceColumn": "Dr Amount",
            "summarizeBy": "none"
          },
          {
            "name": "Cr Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b464567f-2454-47a7-9a08-f1ebd402d96f",
            "sourceColumn": "Cr Amount",
            "summarizeBy": "none"
          },
          {
            "name": "Net Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5aea98b3-7ba4-48d2-818d-a704078e5f6f",
            "sourceColumn": "Net Balance",
            "summarizeBy": "sum"
          },
          {
            "name": "Balance Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb28ae34-f984-41db-bfd9-ae244bde1877",
            "sourceColumn": "Balance Type",
            "summarizeBy": "none"
          },
          {
            "name": "Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c6afa7d7-d586-4732-8d6f-47b50250a677",
            "sourceColumn": "Balance",
            "summarizeBy": "sum"
          },
          {
            "name": "ACT ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a830858b-f7af-4a02-ae79-280d60342902",
            "sourceColumn": "ACT ID",
            "summarizeBy": "none"
          },
          {
            "name": "SA ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "603ee143-3cc5-4bc5-9006-242f7c1ff75a",
            "sourceColumn": "SA ID",
            "summarizeBy": "none"
          },
          {
            "name": "FS ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0432445e-e937-49ca-8e34-55b3b1e66691",
            "sourceColumn": "FS ID",
            "summarizeBy": "none"
          },
          {
            "name": "Account Categories",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "465f030e-05c1-41d4-bbf2-f8d80252c820",
            "sourceColumn": "Account Categories",
            "summarizeBy": "none"
          },
          {
            "name": "Sub Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9517e793-3492-498c-8145-f92682351fbf",
            "sourceColumn": "Sub Account",
            "summarizeBy": "none"
          },
          {
            "name": "Financial Statements",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9336902f-59f0-4316-b922-8894b0df2559",
            "sourceColumn": "Financial Statements",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "19bf7a1a-7138-462e-bff0-d71fefc1f5ee",
        "partitions": [
          {
            "name": "TB",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1YX4WNZQ929nUAyBzTtNhQUisvrJzEYo8\"),[Delimiter=\",\", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Account ID\", type text}, {\"Account Name\", type text}, {\"Dr Amount\", type text}, {\"Cr Amount\", type text}, {\"Net Balance\", Int64.Type}, {\"Balance Type\", type text}, {\"Balance\", Int64.Type}, {\"ACT ID\", type text}, {\"SA ID\", type text}, {\"FS ID\", type text}, {\"Account Categories\", type text}, {\"Sub Account\", type text}, {\"Financial Statements\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Amlan Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e837ef05dd354b2093e53be2d2b47d4e"
          }
        ],
        "columns": [
          {
            "name": "Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "675c8109-b151-4a94-aa50-f47cc89b0a98",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parameter Fields"
                }
              ]
            },
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "cf13d21a-a92f-4417-89d5-37b2b628d0d2",
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "0331ef88-7e5c-43fa-8180-781f7c97666f",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "5b623597-2967-4ab1-973e-761f21202170",
        "partitions": [
          {
            "name": "Amlan Parameter",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Expense\", NAMEOF('Amlan Measure'[Expense]), 0),",
                "    (\"Revenue\", NAMEOF('Amlan Measure'[Revenue]), 1),",
                "    (\"Profit %\", NAMEOF('Amlan Measure'[Profit %]), 2)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}