{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"SAC\",\"JR\",\"FS\",\"AC\",\"JR (2)\",\"TB\",\"SAC_N\",\"JR_N\",\"TB_N\",\"Calendar\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "AutoDetected_28cb9c10-815c-4cde-9846-f9fae58ccb74",
        "fromColumn": "ACT ID",
        "fromTable": "JR",
        "isActive": false,
        "toColumn": "ACT ID",
        "toTable": "AC"
      },
      {
        "name": "AutoDetected_181d66b9-548e-49dc-83e2-aeaa7730f6c2",
        "fromColumn": "SA ID",
        "fromTable": "JR",
        "isActive": false,
        "toColumn": "SA ID",
        "toTable": "SAC"
      },
      {
        "name": "AutoDetected_23ae05ae-a759-4e3b-9be4-60237ca0190f",
        "fromColumn": "FS ID",
        "fromTable": "JR",
        "isActive": false,
        "toColumn": "FS ID",
        "toTable": "FS"
      },
      {
        "name": "6f0caf64-59f7-4ccf-8476-b9553faea6ef",
        "fromColumn": "Date",
        "fromTable": "Calender Amlan",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_fffb432f-616a-4d3f-8023-d865878d3795"
      },
      {
        "name": "3525a65b-3c3d-1938-ac40-89e5c1242e54",
        "fromColumn": "Date",
        "fromTable": "JR",
        "toColumn": "Date",
        "toTable": "Calender Amlan"
      },
      {
        "name": "AutoDetected_b74d74aa-0a4e-4fbc-bce8-b2909aaf5c2d",
        "fromColumn": "Sub Account",
        "fromTable": "TB",
        "toColumn": "Sub Account",
        "toTable": "SAC"
      },
      {
        "name": "AutoDetected_c0b38f7e-34e1-4fbc-95fc-160c54986dfe",
        "fromColumn": "Account Categories",
        "fromTable": "TB",
        "toColumn": "Account Categories",
        "toTable": "AC"
      },
      {
        "name": "AutoDetected_f0c6c605-c7d2-4d9b-b7e1-54f0edf245e0",
        "fromColumn": "Financial Statements",
        "fromTable": "TB",
        "toColumn": "Financial Statements",
        "toTable": "FS"
      },
      {
        "name": "bad9ae6a-328f-42d2-b1c6-d09f4c09b875",
        "fromColumn": "JR.Date",
        "fromTable": "TB",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_33ffe7d0-b056-4a58-ae28-58a1b5df6c1b"
      },
      {
        "name": "AutoDetected_d6ef1357-4bb3-426d-95dc-ea107800f51c",
        "fromColumn": "Sub Account",
        "fromTable": "TB_N",
        "toColumn": "Sub Account",
        "toTable": "SAC"
      },
      {
        "name": "AutoDetected_7fb49b83-784f-425d-bf62-8360950b1b8d",
        "fromColumn": "ACT ID",
        "fromTable": "TB_N",
        "toColumn": "ACT ID",
        "toTable": "AC"
      },
      {
        "name": "AutoDetected_e236d17a-ee84-4351-a337-b7cc9eb92b13",
        "fromColumn": "FS ID",
        "fromTable": "TB_N",
        "toColumn": "FS ID",
        "toTable": "FS"
      },
      {
        "name": "175c383c-d124-e595-c2f6-c18de7e907f3",
        "fromColumn": "FS ID",
        "fromTable": "JR_N",
        "isActive": false,
        "toColumn": "FS ID",
        "toTable": "FS"
      },
      {
        "name": "5c51f80f-e6f3-da43-6b0e-d5000dffd6ba",
        "fromColumn": "ACT ID",
        "fromTable": "JR_N",
        "toColumn": "ACT ID",
        "toTable": "AC"
      },
      {
        "name": "fc3cce51-0553-0496-d64d-be68241d6c5d",
        "fromColumn": "Date",
        "fromTable": "JR_N",
        "toColumn": "Date",
        "toTable": "Calender Amlan"
      },
      {
        "name": "AutoDetected_a33e9b90-4b7a-422c-9ada-a6ad1486e453",
        "fromColumn": "Sub Account",
        "fromTable": "JR",
        "toColumn": "Sub Account",
        "toTable": "SAC_N"
      },
      {
        "name": "AutoDetected_132cbc65-be81-4315-a351-7e10b9fbfa22",
        "fromColumn": "Sub Account",
        "fromTable": "TB",
        "isActive": false,
        "toColumn": "Sub Account",
        "toTable": "SAC_N"
      },
      {
        "name": "AutoDetected_cb13b04b-bd5a-4544-8bea-de78427343e0",
        "fromColumn": "Sub Account",
        "fromTable": "TB_N",
        "toColumn": "Sub Account",
        "toTable": "SAC_N"
      },
      {
        "name": "7c60a20d-3ac5-177d-dea7-058ba5259cf0",
        "fromColumn": "SA ID",
        "fromTable": "JR_N",
        "toColumn": "SA ID",
        "toTable": "SAC_N"
      },
      {
        "name": "173a8e23-f45f-4215-55bd-929bb3c0022e",
        "fromColumn": "SA ID",
        "fromTable": "JR_N",
        "isActive": false,
        "toColumn": "SA ID",
        "toTable": "SAC"
      },
      {
        "name": "43224601-5d67-49f8-9e4e-628d541f0b03",
        "fromColumn": "Start of Month",
        "fromTable": "JR_N",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_6e92fd0d-537d-46d8-bda8-760b71513fd5"
      },
      {
        "name": "4138cc42-fb35-53d4-c633-6d354a9cbccd",
        "fromColumn": "Account Name",
        "fromTable": "JR",
        "toColumn": "Account Name",
        "toTable": "JR (2)"
      },
      {
        "name": "4b706daf-94f5-49ac-8899-a0acde9960ee",
        "fromColumn": "Date",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_22be8054-467e-4a80-a821-4528173dc1a7"
      },
      {
        "name": "50ad80d2-5565-88ef-3478-ccb04871d2b8",
        "fromColumn": "Date",
        "fromTable": "JR",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "4e31dd3f-4edf-a52d-04b3-720a966df53f",
        "fromColumn": "Date",
        "fromTable": "JR_N",
        "toColumn": "Date",
        "toTable": "Calendar"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_8ed80194-b6af-4d9e-aea3-168b294007bc",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "27568a21-3a7f-49c6-92bd-135c40ed096b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "13401607-e72b-4c7c-a4b4-283fee2959e7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "a2f310ab-4693-4daa-bd47-c755df0383d1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0b897692-7116-4e8d-85ee-73072e2c725a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "765516c8-4a36-4363-9446-8ffd16b7e6f5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "8fa0dc19-07c3-4d2e-b35f-d18c7a614400",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "70ab9782-4bbe-40bd-baa9-c056868b46e5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "073b9e4f-ead9-4bf7-a22b-b42bd6a47624",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "688d3801-70f1-4197-82a0-b1de17835642",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6c2454a3-3cd7-4571-b033-c92c8d4638ea",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b3412ee7-d2ed-445a-97fe-1419c99922ec",
                "ordinal": 3
              }
            ],
            "lineageTag": "6041a11d-3c73-409b-af2e-bc7977830e8d"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "2d06b31a-9ddb-4580-9333-a73b9dacbe16",
        "partitions": [
          {
            "name": "DateTableTemplate_8ed80194-b6af-4d9e-aea3-168b294007bc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Amlan Measure",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a28ced9fe5584483b4fb40b9d17da897"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b22948df-5dce-425f-8a89-be5242635758",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "12f7527c-2749-4318-9a01-9d94c1881cea",
        "measures": [
          {
            "name": "Total Balance",
            "expression": "SUM(JR[Balance])",
            "formatString": "0",
            "lineageTag": "a061e28a-8d09-46e6-b554-334eba1f0d6d"
          },
          {
            "name": "Total Revenue",
            "expression": "CALCULATE(SUM(JR[Balance]),FILTER(JR,JR[Account Categories]=\"Revenue\"))",
            "formatString": "0",
            "lineageTag": "889bcdbe-dab2-43b0-bde4-d1ec407c2285"
          },
          {
            "name": "Total Expense",
            "expression": "CALCULATE(SUM(JR[Balance]),FILTER(JR,JR[Account Categories]=\"Expense\"))",
            "formatString": "0",
            "lineageTag": "ee985a27-9c1f-4555-83a6-12cdbc656526"
          },
          {
            "name": "Net Profit",
            "expression": "[Total Revenue] - [Total Expense]",
            "formatString": "0.00",
            "lineageTag": "5b2e25d3-ce6a-4e26-a47a-ef1db72ed66b"
          },
          {
            "name": "Profit Loss Variance",
            "expression": [
              "",
              "VAR Uparrow = UNICHAR(129137)",
              "VAR Downarrow = UNICHAR(129139)",
              "",
              "RETURN",
              "    IF([Net Profit] > 0,Uparrow,Downarrow)",
              ""
            ],
            "lineageTag": "70ca83ac-a616-46ae-bfdd-df9b93d8bd3f"
          },
          {
            "name": "Previous Y",
            "expression": [
              "",
              "VAR SelectedYear = ",
              "    MAX('Calender Amlan'[Year]) // Using MAX to ensure a single year is selected",
              "RETURN",
              "IF(",
              "    NOT ISBLANK(SelectedYear), ",
              "    CALCULATE(",
              "        SUM(JR[Balance]),",
              "        'Calender Amlan'[Year] = SelectedYear - 1,",
              "        REMOVEFILTERS('Calender Amlan') // Ensuring no other filters interfere",
              "    ),",
              "    BLANK()",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "fb83015a-86f7-45f2-a3a5-72b25efd6002"
          },
          {
            "name": "Profit %",
            "expression": "[Net Profit] / [Total Revenue]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0063cecf-3218-4f53-8224-3c96577d5515"
          },
          {
            "name": "Var %",
            "expression": "DIVIDE([Total Balance] - [Previous Y],[Total Balance])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4eb67a18-3bfd-4c35-881a-4d2cc6d9151b"
          },
          {
            "name": "AVG Inventory",
            "expression": "CALCULATE(SUM(TB[Balance]),TB[Account Name] = \"Inventory\") / 2",
            "formatString": "0.00",
            "lineageTag": "35447e64-6df2-4b4c-a619-b79722ac2edd"
          },
          {
            "name": "Total COGS",
            "expression": "CALCULATE([Total Balance],JR[Account Name] = \"COGS\")",
            "formatString": "0",
            "lineageTag": "556d5e36-6415-4eeb-8429-7824ebd5f644"
          },
          {
            "name": "Invt. Turn Ratio",
            "expression": "DIVIDE([Total COGS],[AVG Inventory])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a5e77d47-48fa-4367-9c7f-c214398be210"
          },
          {
            "name": "Avg Inventory Days",
            "expression": "DIVIDE([AVG Inventory],[Total COGS]) * 365",
            "formatString": "0",
            "lineageTag": "15c13904-4780-4b3a-9bf2-75b8b449d4ea"
          },
          {
            "name": "Current Assets",
            "expression": "CALCULATE(SUM(TB[Balance]),TB,TB[Sub Account] = \"Current Assets\")",
            "formatString": "0.00",
            "lineageTag": "0c43954e-1147-495c-843f-fd9334341c6c"
          },
          {
            "name": "Current Liabilities",
            "expression": "CALCULATE(SUM(TB[Balance]),TB,TB[Sub Account]=\"Current Liabilities\" )",
            "formatString": "0.00",
            "lineageTag": "6f5c5285-5cad-408a-a0cd-2167cae1e371"
          },
          {
            "name": "WC Ratio",
            "expression": "DIVIDE([Current Assets],[Current Liabilities]) ",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "dd826be5-9762-49ac-a91a-ad83a338051e"
          }
        ],
        "partitions": [
          {
            "name": "Amlan Measure",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "SAC",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Sub Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "473f1a23-5c38-4da9-abab-9fc6080a59ac",
            "sourceColumn": "Sub Account",
            "summarizeBy": "none"
          },
          {
            "name": "SA ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04d05a0d-dd2b-4384-a5ad-d5e869f2a95f",
            "sourceColumn": "SA ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6a314796-567e-4848-988d-f0c6b01c909f",
        "partitions": [
          {
            "name": "SAC",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\" https://drive.google.com/uc?export=download&id=1Aq8j52GBzqpjmTRtZdKTkQnbRZF9R_E8\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Sub Account\", type text}, {\"SA ID\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "JR",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Journal ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97be3e8d-d03a-4990-bc27-a183b2b04357",
            "sourceColumn": "Journal ID",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "edb08008-2afc-4456-85f0-a9da589ca34c",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Account ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a9158b2-dbf6-4254-a147-595cb2190c49",
            "sourceColumn": "Account ID",
            "summarizeBy": "none"
          },
          {
            "name": "Dr Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "d9ea5e26-8596-4398-b053-63153f92a9bd",
            "sourceColumn": "Dr Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Cr Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "89ddc322-e4b7-450d-8292-6a9224fb6dcf",
            "sourceColumn": "Cr Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Details",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8800e602-1273-4bbc-8d8e-2a4e0ef2e347",
            "sourceColumn": "Details",
            "summarizeBy": "none"
          },
          {
            "name": "Cash flow statement operator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50391b48-930b-4cee-b820-afcac84c8530",
            "sourceColumn": "Cash flow statement operator",
            "summarizeBy": "none"
          },
          {
            "name": "Cash flow Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6aa9be88-6c1f-414e-9f33-886c2cd08ce2",
            "sourceColumn": "Cash flow Status",
            "summarizeBy": "none"
          },
          {
            "name": "Cash flow Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "74f957f6-3650-4d0e-81e7-dc158d034d9f",
            "sourceColumn": "Cash flow Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "ACT ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7aa8e0c-7001-444d-a4bc-6dd040e76690",
            "sourceColumn": "ACT ID",
            "summarizeBy": "none"
          },
          {
            "name": "SA ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e75e1c5-d556-4271-a468-0143f8554408",
            "sourceColumn": "SA ID",
            "summarizeBy": "none"
          },
          {
            "name": "FS ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e685e6e9-7fb2-467f-b5c9-f581a1f081bc",
            "sourceColumn": "FS ID",
            "summarizeBy": "none"
          },
          {
            "name": "Account Categories",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2f83890-861f-4ca3-907e-b12d5950bbc6",
            "sourceColumn": "Account Categories",
            "summarizeBy": "none"
          },
          {
            "name": "Sub Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cfa6264b-4232-42f4-83f6-2998031248f8",
            "sourceColumn": "Sub Account",
            "summarizeBy": "none"
          },
          {
            "name": "Financial Statements",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5278b739-b2c4-4ccf-bd1f-7c90a42c5118",
            "sourceColumn": "Financial Statements",
            "summarizeBy": "none"
          },
          {
            "name": "Account Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd1229a9-debc-428a-8fb9-9521627f37a2",
            "sourceColumn": "Account Name",
            "summarizeBy": "none"
          },
          {
            "name": "Net Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "f2543210-2594-4977-971f-a845dcc6489b",
            "sourceColumn": "Net Balance",
            "summarizeBy": "sum"
          },
          {
            "name": "Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "21c99497-06a2-46b8-a2f0-6ef1478c5248",
            "sourceColumn": "Balance",
            "summarizeBy": "sum"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(JR[Date],\"MMM\")",
            "lineageTag": "0a5901cf-fe1d-4529-b71f-92cb6233259a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "expression": "FORMAT(JR[Date],\"YYYY\")",
            "formatString": "0",
            "lineageTag": "083e4925-6a34-4e9a-9bbb-a6714fa5c103",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "cash flow Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    CONTAINSSTRING(JR[Details], \"equipment\"), \"Investing Activities\",",
              "    CONTAINSSTRING(JR[Details], \"vehicle\"), \"Investing Activities\",",
              "    CONTAINSSTRING(JR[Details], \"machinery\"), \"Investing Activities\",",
              "    CONTAINSSTRING(JR[Details], \"Loan received\"), \"Financing Activities\",",
              "    CONTAINSSTRING(JR[Details], \"Capital contribution\"), \"Financing Activities\",",
              "    CONTAINSSTRING(JR[Details], \"Loan repayment\"), \"Financing Activities\",",
              "    CONTAINSSTRING(JR[Details], \"rent\"), \"Operating Activities\",",
              "    CONTAINSSTRING(JR[Details], \"utility\"), \"Operating Activities\",",
              "    CONTAINSSTRING(JR[Details], \"inventory\"), \"Operating Activities\",CONTAINSSTRING(JR[Details], \"inventoy\"), \"Operating Activities\",CONTAINSSTRING(JR[Details], \"Utilities bill\"), \"Operating Activities\",CONTAINSSTRING(JR[Details], \"Received payment from customer\"), \"Operating Activities\",",
              "    CONTAINSSTRING(JR[Details], \"sales\"), \"Operating Activities\",",
              "    CONTAINSSTRING(JR[Details], \"advertising\"), \"Operating Activities\",",
              "    CONTAINSSTRING(JR[Details], \"salaries\"), \"Operating Activities\",",
              "    CONTAINSSTRING(JR[Details], \"tax\"), \"Operating Activities\",",
              "    CONTAINSSTRING(JR[Details], \"office supplies\"), \"Operating Activities\",",
              "    CONTAINSSTRING(JR[Details], \"services\"), \"Operating Activities\",",
              "    CONTAINSSTRING(JR[Details], \"Repairs\"), \"Operating Activities\",",
              "    \"Other\"",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "8b2d58e9-3e50-41e9-8bce-b3ad591646f6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "abd19040-da3a-4b83-ab99-b0c329457115",
        "partitions": [
          {
            "name": "JR",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1muzBTVjMEq2UeiAlJJaukjfNBAGYfCFB\"),[Delimiter=\",\", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Journal ID\", type text}, {\"Date\", type date}, {\"Account Name\", type text}, {\"Account ID\", type text}, {\"Dr Amount\", Int64.Type}, {\"Cr Amount\", Int64.Type}, {\"Details\", type text}, {\"Cash flow statement operator\", type text}, {\"Cash flow Status\", type text}, {\"Cash flow Amount\", Int64.Type}, {\"ACT ID\", type text}, {\"SA ID\", type text}, {\"FS ID\", type text}, {\"Account Categories\", type text}, {\"Sub Account\", type text}, {\"Financial Statements\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",null,0,Replacer.ReplaceValue,{\"Journal ID\", \"Dr Amount\", \"Cr Amount\", \"Cash flow Amount\"}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Replaced Value\", \"New\", each if [Account Name] = \"Cash at bank\" then \"Cash at Bank\" else if [Account Name] = \"Utility expense\" then \"Utility Expense\" else null),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Conditional Column\",{\"Journal ID\", \"Date\", \"Account Name\", \"New\", \"Account ID\", \"Dr Amount\", \"Cr Amount\", \"Details\", \"Cash flow statement operator\", \"Cash flow Status\", \"Cash flow Amount\", \"ACT ID\", \"SA ID\", \"FS ID\", \"Account Categories\", \"Sub Account\", \"Financial Statements\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns\",{\"New\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Removed Columns\", \"New\", each if [Account Name] = \"Cash at bank\" then \"Cash at Bank\" else",
                "if [Account Name] = \"Utility expense\" then \"Utility Expense\" else [Account Name]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Custom\",{{\"Account Name\", \"Account Name 2\"}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Renamed Columns\",{\"Account Name 2\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"New\", \"Account Name\"}}),",
                "    #\"Inserted Subtraction\" = Table.AddColumn(#\"Renamed Columns1\", \"Subtraction\", each [Dr Amount] - [Cr Amount], type number),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Inserted Subtraction\",{{\"Subtraction\", \"Net Balance\"}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Renamed Columns2\", \"Balance\", each if [Net Balance] < 0 then [Net Balance] *-1 else ",
                "[Net Balance]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"Balance\", Int64.Type}, {\"Net Balance\", Int64.Type}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Financial Statements",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7965ca3c-bf02-4ebc-9254-34bde914ee92",
            "sourceColumn": "Financial Statements",
            "summarizeBy": "none"
          },
          {
            "name": "FS ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b9ce341-3f1e-4810-9628-2154a928bf5d",
            "sourceColumn": "FS ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f88f0929-8074-479b-b77f-8929649fb6e2",
        "partitions": [
          {
            "name": "FS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1Jt_zDhxd6l5jsXbtHF3mrwiqjpDtLl8M\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Financial Statements\", type text}, {\"FS ID\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "AC",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Account Categories",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adca4cf3-7f35-4a49-b443-f0328e603d52",
            "sourceColumn": "Account Categories",
            "summarizeBy": "none"
          },
          {
            "name": "ACT ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02e35365-57ba-424b-8ef4-88d7e625744e",
            "sourceColumn": "ACT ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8251ad68-695e-49a5-9505-b7717c6c5a08",
        "partitions": [
          {
            "name": "AC",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1A3Q8n4q8aFdxMavB4gum-sb65yEuWE3u\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Account Categories\", type text}, {\"ACT ID\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calender Amlan",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f366a225a6e24111bb43e47e8b2d9679"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "162a01c6-57ba-4304-8f53-3c7639f211f8",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_fffb432f-616a-4d3f-8023-d865878d3795"
                },
                "isDefault": true,
                "relationship": "6f0caf64-59f7-4ccf-8476-b9553faea6ef"
              }
            ]
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "FORMAT('Calender Amlan'[Date],\"MM\")",
            "formatString": "0",
            "lineageTag": "86ca8217-d162-4de0-84c2-dfe162ac2cdf",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "FORMAT('Calender Amlan'[Date],\"YYYY\")",
            "formatString": "0",
            "lineageTag": "c0e1b1b0-766f-4f55-8f4f-1b7750f03499",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "497aed6c-7065-47a3-8157-29716497dd02",
        "partitions": [
          {
            "name": "Calender Amlan",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(MIN(JR[Date]),MAX(JR[Date]))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_fffb432f-616a-4d3f-8023-d865878d3795",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d5c561d6-6e15-4246-afc6-9cbaa499a4ef",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "385058a6-d3d9-439d-b42c-f7431c463d30",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "790072bf-9340-4ee2-ba8a-a27ee853e445",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8337c876-a11c-431d-90a7-abee2a6413fb",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "7269671f-b372-42f1-a865-c24bcaa8b3c7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "3728cc2a-e862-4413-9b43-8c7372276383",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "735120b1-fb80-41e6-8d62-d43970a3f7b6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5965a636-133f-427b-9a49-a2ef53a1c095",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f2a0fb71-0499-4543-8fa9-b4137907f5f9",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "bd653f58-d6e5-4c30-96ea-c07c5b1826a3",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "8d783931-b84d-4395-b01e-94327fc33ad5",
                "ordinal": 3
              }
            ],
            "lineageTag": "1fdc4650-df07-4eeb-8b01-a16f5dfd67bb"
          }
        ],
        "isHidden": true,
        "lineageTag": "19524faf-7514-4ef9-b94e-0cf669a8f0bd",
        "partitions": [
          {
            "name": "LocalDateTable_fffb432f-616a-4d3f-8023-d865878d3795",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calender Amlan'[Date])), 1, 1), Date(Year(MAX('Calender Amlan'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Amlan Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ead96bc2bbc24ab59f9e25c4def4cde4"
          }
        ],
        "columns": [
          {
            "name": "Amlan Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "58718cb6-4e84-4b98-a1b6-633d63228cf0",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Amlan Parameter Fields"
                }
              ]
            },
            "sortByColumn": "Amlan Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Amlan Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "f8eb13d3-c979-44fa-bafc-3a1c23dca2fc",
            "sortByColumn": "Amlan Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Amlan Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "ea0fcfd9-b2f1-4ba8-8124-328b876487e9",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "ec787141-1701-49ff-a9e0-7026b180fc58",
        "partitions": [
          {
            "name": "Amlan Parameter",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Total Expense\", NAMEOF('Amlan Measure'[Total Expense]), 0),",
                "    (\"Total Revenue\", NAMEOF('Amlan Measure'[Total Revenue]), 1),",
                "    (\"Profit %\", NAMEOF('Amlan Measure'[Profit %]), 2)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Amlan 2 Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "55b9ce9fde2e4bc48a9c3b03398c31e7"
          }
        ],
        "columns": [
          {
            "name": "Amlan 2 Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "fc70c1bc-c9b3-4235-829b-cecb86367fb7",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Amlan 2 Parameter Fields"
                }
              ]
            },
            "sortByColumn": "Amlan 2 Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Amlan 2 Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "7ee5663a-ab09-4eac-8897-64582a372fe3",
            "sortByColumn": "Amlan 2 Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Amlan 2 Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "a0d778b9-3faf-48fd-afb5-cfb5884e3984",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "eedaba8f-f9db-4d72-a8fe-6f3bd91a4a82",
        "partitions": [
          {
            "name": "Amlan 2 Parameter",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Total Balance\", NAMEOF('Amlan Measure'[Total Balance]), 0),",
                "    (\"Previous Y\", NAMEOF('Amlan Measure'[Previous Y]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "JR (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Account Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4c61b39-3809-4d2c-9c98-37718276a6fd",
            "sourceColumn": "Account Name",
            "summarizeBy": "none"
          },
          {
            "name": "Dr Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ec5dbd23-015e-4dfa-ade6-085d2d14ad50",
            "sourceColumn": "Dr Amount",
            "summarizeBy": "none"
          },
          {
            "name": "Cr Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b03619f2-f5f0-43fd-875d-75a3ed5dcfe1",
            "sourceColumn": "Cr Amount",
            "summarizeBy": "none"
          },
          {
            "name": "Net Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d972db1f-aba5-459d-87c1-f757f367ba36",
            "sourceColumn": "Net Balance",
            "summarizeBy": "none"
          },
          {
            "name": "Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ceec67b-7179-486b-bc24-2a860569d2e8",
            "sourceColumn": "Balance",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e51dc2dc-e5aa-42bc-a5aa-e0ae1a3cefd8",
        "partitions": [
          {
            "name": "JR (2)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1muzBTVjMEq2UeiAlJJaukjfNBAGYfCFB\"),[Delimiter=\",\", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Journal ID\", type text}, {\"Date\", type date}, {\"Account Name\", type text}, {\"Account ID\", type text}, {\"Dr Amount\", Int64.Type}, {\"Cr Amount\", Int64.Type}, {\"Details\", type text}, {\"Cash flow statement operator\", type text}, {\"Cash flow Status\", type text}, {\"Cash flow Amount\", Int64.Type}, {\"ACT ID\", type text}, {\"SA ID\", type text}, {\"FS ID\", type text}, {\"Account Categories\", type text}, {\"Sub Account\", type text}, {\"Financial Statements\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",null,0,Replacer.ReplaceValue,{\"Journal ID\", \"Dr Amount\", \"Cr Amount\", \"Cash flow Amount\"}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Replaced Value\", \"New\", each if [Account Name] = \"Cash at bank\" then \"Cash at Bank\" else if [Account Name] = \"Utility expense\" then \"Utility Expense\" else null),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Conditional Column\",{\"Journal ID\", \"Date\", \"Account Name\", \"New\", \"Account ID\", \"Dr Amount\", \"Cr Amount\", \"Details\", \"Cash flow statement operator\", \"Cash flow Status\", \"Cash flow Amount\", \"ACT ID\", \"SA ID\", \"FS ID\", \"Account Categories\", \"Sub Account\", \"Financial Statements\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns\",{\"New\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Removed Columns\", \"New\", each if [Account Name] = \"Cash at bank\" then \"Cash at Bank\" else",
                "if [Account Name] = \"Utility expense\" then \"Utility Expense\" else [Account Name]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Custom\",{{\"Account Name\", \"Account Name 2\"}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Renamed Columns\",{\"Account Name 2\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"New\", \"Account Name\"}}),",
                "    #\"Inserted Subtraction\" = Table.AddColumn(#\"Renamed Columns1\", \"Subtraction\", each [Dr Amount] - [Cr Amount], type number),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Inserted Subtraction\",{{\"Subtraction\", \"Net Balance\"}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Renamed Columns2\", \"Balance\", each if [Net Balance] < 0 then [Net Balance] *-1 else ",
                "[Net Balance]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"Balance\", Int64.Type}, {\"Net Balance\", Int64.Type}}),",
                "    #\"Grouped Rows\" = Table.Group(#\"Changed Type1\", {\"Account Name\"}, {{\"Dr Amount\", each List.Sum([Dr Amount]), type nullable number}, {\"Cr Amount\", each List.Sum([Cr Amount]), type nullable number}}),",
                "    #\"Inserted Subtraction1\" = Table.AddColumn(#\"Grouped Rows\", \"Subtraction\", each [Dr Amount] - [Cr Amount], type number),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Inserted Subtraction1\",{{\"Subtraction\", \"Net Balance\"}}),",
                "    #\"Added Custom2\" = Table.AddColumn(#\"Renamed Columns3\", \"Balance\", each if [Net Balance] < 0 then [Net Balance] *-1 else ",
                "[Net Balance])",
                "in",
                "    #\"Added Custom2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TB",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Account Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57af212d-c366-45e8-ad62-25b448d3c499",
            "sourceColumn": "Account Name",
            "summarizeBy": "none"
          },
          {
            "name": "Account Categories",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "53376385-bac3-4475-a326-e6055bb9c712",
            "sourceColumn": "Account Categories",
            "summarizeBy": "none"
          },
          {
            "name": "Sub Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07924558-3312-4e1c-a39c-b1b6a83db1d3",
            "sourceColumn": "Sub Account",
            "summarizeBy": "none"
          },
          {
            "name": "Financial Statements",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f22a6f6-7000-4330-9981-3548decb5681",
            "sourceColumn": "Financial Statements",
            "summarizeBy": "none"
          },
          {
            "name": "Dr Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5f58315a-02db-4b82-8cb2-fcadd2706a79",
            "sourceColumn": "Dr Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Cr Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "532dc6e1-794a-4fb5-9f94-d0dcf022cd99",
            "sourceColumn": "Cr Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Net Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "c9901e97-0515-4adc-86a9-5656bfb0261f",
            "sourceColumn": "Net Balance",
            "summarizeBy": "sum"
          },
          {
            "name": "Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a4c40087-5456-421d-98f8-7882324aace3",
            "sourceColumn": "Balance",
            "summarizeBy": "sum"
          },
          {
            "name": "JR.Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "1e66745d-5e73-4fea-84c6-3870be3bd407",
            "sourceColumn": "JR.Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_33ffe7d0-b056-4a58-ae28-58a1b5df6c1b"
                },
                "isDefault": true,
                "relationship": "bad9ae6a-328f-42d2-b1c6-d09f4c09b875"
              }
            ]
          }
        ],
        "lineageTag": "513c9dff-76c3-4f8e-b018-93f4618cfa4d",
        "partitions": [
          {
            "name": "TB",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.NestedJoin(#\"JR (2)\", {\"Account Name\"}, JR, {\"Account Name\"}, \"JR\", JoinKind.LeftOuter),",
                "    #\"Expanded JR\" = Table.ExpandTableColumn(Source, \"JR\", {\"Account Categories\", \"Sub Account\", \"Financial Statements\"}, {\"JR.Account Categories\", \"JR.Sub Account\", \"JR.Financial Statements\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Expanded JR\", {\"Account Name\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Duplicates\",{{\"JR.Account Categories\", \"Account Categories\"}, {\"JR.Sub Account\", \"Sub Account\"}, {\"JR.Financial Statements\", \"Financial Statements\"}}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Renamed Columns\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Index\",{\"Index\"}),",
                "    #\"Added Index1\" = Table.AddIndexColumn(#\"Removed Columns\", \"Index\", 0, 1, Int64.Type),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Added Index1\",{\"Index\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Removed Columns1\",{\"Account Name\", \"Account Categories\", \"Sub Account\", \"Financial Statements\", \"Dr Amount\", \"Cr Amount\", \"Net Balance\", \"Balance\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Reordered Columns\",{{\"Balance\", Int64.Type}, {\"Net Balance\", Int64.Type}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Changed Type\", {\"Account Name\"}, JR, {\"Account Name\"}, \"JR\", JoinKind.LeftOuter),",
                "    #\"Expanded JR1\" = Table.ExpandTableColumn(#\"Merged Queries\", \"JR\", {\"Date\"}, {\"JR.Date\"}),",
                "    #\"Removed Duplicates1\" = Table.Distinct(#\"Expanded JR1\", {\"Account Name\"})",
                "in",
                "    #\"Removed Duplicates1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_33ffe7d0-b056-4a58-ae28-58a1b5df6c1b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5db5346f-2117-45df-8517-750d505ae8c5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "e6f09869-1ef2-4375-bf35-280efc13e8a6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "f884076f-ba1e-4c20-8c52-4a213405a8da",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "4a138649-6c4e-4c41-923c-9ef8f7382f8a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "55fa7aca-5e5b-4ab5-a1ca-fbf9d6f2805b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "1d8d8ec2-8908-476c-b96f-a8820dd5fea5",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "76aabdd3-5d61-4722-814d-6fb15c8958c9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "6902bd1c-b06a-49e1-bdf6-8f2dc9bb2204",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "4e6fc45f-765b-41f6-8340-83f891f027dc",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b13de0f7-d2fd-4630-bf30-950daee2cd4a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "7bbc272e-5124-4067-94ad-b6aa83240dab",
                "ordinal": 3
              }
            ],
            "lineageTag": "0d0a8c36-e188-413c-8450-1e38c2fe668a"
          }
        ],
        "isHidden": true,
        "lineageTag": "fb7793b8-e61a-4609-b2f8-07146cb2230a",
        "partitions": [
          {
            "name": "LocalDateTable_33ffe7d0-b056-4a58-ae28-58a1b5df6c1b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('TB'[JR.Date])), 1, 1), Date(Year(MAX('TB'[JR.Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Badsha Measure",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "349b368fd2ab4a1eacfa425cdf4ddc3d"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "21b14175-b46c-4b0e-8681-f82678295020",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "8287e415-185b-4b08-988d-a2fbef8931ab",
        "measures": [
          {
            "name": "Year",
            "lineageTag": "be70991d-195f-4ced-9060-db6dde1a5b19"
          }
        ],
        "partitions": [
          {
            "name": "Badsha Measure",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Ashraf Measure",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b5373eb6642842919b43808842ac99b7"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8728ae7b-bfa2-4e5d-8f38-3b1114a56529",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "0cd8a0ec-ad86-41b4-bcea-822214aca2ac",
        "measures": [
          {
            "name": "cash inflow",
            "expression": "CALCULATE(SUM(JR[Balance]),FILTER(JR,JR[Cash flow Status]=\"Cash Inflow\"))",
            "formatString": "0.00",
            "lineageTag": "a6d2a20f-3e12-4f5b-b9ec-033122981226"
          },
          {
            "name": "cash outflow",
            "expression": "CALCULATE(SUM(JR[Balance]),FILTER(JR,JR[Cash flow Status]=\"Cash Outfow\"))",
            "formatString": "0.00",
            "lineageTag": "e22d3b6f-3043-4c18-90ae-12a4d78d880d"
          }
        ],
        "partitions": [
          {
            "name": "Ashraf Measure",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "SAC_N",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Sub Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b7bdb4e-3fa4-4dff-a3e1-12983b993ebd",
            "sourceColumn": "Sub Account",
            "summarizeBy": "none"
          },
          {
            "name": "SA ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ac124ed-2879-4d07-80ce-52d79f59e47a",
            "sourceColumn": "SA ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5ba2f45e-4235-4469-bad5-9fbf73216c94",
        "partitions": [
          {
            "name": "SAC_N",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1d-D9mC-L5gJH1pwDzl6CeGtLEIonccte\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Sub Account\", type text}, {\"SA ID\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "JR_N",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Journal ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "16ad13e0-0bba-4b94-802d-16a53c91ce4d",
            "sourceColumn": "Journal ID",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6fa41f77-ab3e-482a-b964-ace3e45ae2ad",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Account Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a6f1cae-7445-4757-a542-aa899831c2c5",
            "sourceColumn": "Account Name",
            "summarizeBy": "none"
          },
          {
            "name": "Dr Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "886ce78b-e8fa-42ca-963d-299dce7ea457",
            "sourceColumn": "Dr Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Cr Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "8acafce8-d3c2-4107-a64b-c49efd0aa51d",
            "sourceColumn": "Cr Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Details",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "936cadd0-05ec-46c5-8fe9-180d91a15732",
            "sourceColumn": "Details",
            "summarizeBy": "none"
          },
          {
            "name": "Cash flow statement operator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b901773f-582f-4284-9d5c-07b013abbc06",
            "sourceColumn": "Cash flow statement operator",
            "summarizeBy": "none"
          },
          {
            "name": "Cash flow Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "de8c1cf0-136a-4dcc-b5a0-69c2cd764ca4",
            "sourceColumn": "Cash flow Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "ACT ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b021d6d-4f00-48d1-91b6-653bc9339479",
            "sourceColumn": "ACT ID",
            "summarizeBy": "none"
          },
          {
            "name": "SA ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1124fcb-f349-46c0-87e1-3f1a7d0c28bf",
            "sourceColumn": "SA ID",
            "summarizeBy": "none"
          },
          {
            "name": "FS ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc30b1c1-ddee-4fd9-b718-85cc7bcb9397",
            "sourceColumn": "FS ID",
            "summarizeBy": "none"
          },
          {
            "name": "Account Categories",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7912d4ad-928b-4a80-b6e9-35eecead24b0",
            "sourceColumn": "Account Categories",
            "summarizeBy": "none"
          },
          {
            "name": "Sub Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5c5bbad-8028-4346-9ae3-e5d8a7a29162",
            "sourceColumn": "Sub Account",
            "summarizeBy": "none"
          },
          {
            "name": "Financial Statements",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2109cf09-aefa-4c64-9b53-bb0f1082e765",
            "sourceColumn": "Financial Statements",
            "summarizeBy": "none"
          },
          {
            "name": "Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3be8c069-014a-4348-8d39-66c2c0692c14",
            "sourceColumn": "Balance",
            "summarizeBy": "sum"
          },
          {
            "name": "Net Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "46970995-2c74-4a03-8800-587b644d06df",
            "sourceColumn": "Net Balance",
            "summarizeBy": "sum"
          },
          {
            "name": "Start of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1f47f007-0eae-494b-b1c3-29d7c69d6876",
            "sourceColumn": "Start of Month",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_6e92fd0d-537d-46d8-bda8-760b71513fd5"
                },
                "isDefault": true,
                "relationship": "43224601-5d67-49f8-9e4e-628d541f0b03"
              }
            ]
          }
        ],
        "lineageTag": "698f91cb-afe3-4475-a50b-365ad2d15231",
        "partitions": [
          {
            "name": "JR_N",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1v0FZwY8rncl1QWTZGffaS0OZ275GfIVM \"),[Delimiter=\",\", Columns=14, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Journal ID\", type text}, {\"Date\", Int64.Type}, {\"Account Name\", type text}, {\"Dr Amount\", Int64.Type}, {\"Cr Amount\", Int64.Type}, {\"Details\", type text}, {\"Cash flow statement operator\", type text}, {\"Cash flow Amount\", Int64.Type}, {\"ACT ID\", type text}, {\"SA ID\", type text}, {\"FS ID\", type text}, {\"Account Categories\", type text}, {\"Sub Account\", type text}, {\"Financial Statements\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",null,\"0\",Replacer.ReplaceValue,{\"Journal ID\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",null,0,Replacer.ReplaceValue,{\"Dr Amount\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",null,0,Replacer.ReplaceValue,{\"Cr Amount\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Replaced Value2\", \"Balance\", each [Cr Amount]-[Dr Amount]),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Added Custom\", \"Net Balance\", each if [Balance] < 0 then [Balance]*-1 else [Balance]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"Balance\", Int64.Type}, {\"Net Balance\", Int64.Type}, {\"Date\", type date}}),",
                "    #\"Inserted Start of Month\" = Table.AddColumn(#\"Changed Type1\", \"Start of Month\", each Date.StartOfMonth([Date]), type date),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Inserted Start of Month\",{{\"Start of Month\", type date}})",
                "in",
                "    #\"Changed Type2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TB_N",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Account ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a3ca142-0a5b-4a92-9ade-538cf8c20e2f",
            "sourceColumn": "Account ID",
            "summarizeBy": "none"
          },
          {
            "name": "Account Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6bf771d-ff56-4b35-8950-d3c4539c806f",
            "sourceColumn": "Account Name",
            "summarizeBy": "none"
          },
          {
            "name": "Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c9e64e70-d45b-44f3-b9f9-dfa92056e323",
            "sourceColumn": "Balance",
            "summarizeBy": "sum"
          },
          {
            "name": "Balance Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11c094c8-d0c6-4345-8cc0-77c6335a48c3",
            "sourceColumn": "Balance Type",
            "summarizeBy": "none"
          },
          {
            "name": "Final Balance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c89f4460-8396-49b0-8652-3fb26b94bdb2",
            "sourceColumn": "Final Balance",
            "summarizeBy": "sum"
          },
          {
            "name": "ACT ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5529eb33-2e60-4048-be12-0c5d07d8ba19",
            "sourceColumn": "ACT ID",
            "summarizeBy": "none"
          },
          {
            "name": "SA ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "feaa5d05-47bd-4427-8e8f-63c5a5a0975b",
            "sourceColumn": "SA ID",
            "summarizeBy": "none"
          },
          {
            "name": "FS ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08ee5d6b-548b-4162-96fc-758d74f60bbf",
            "sourceColumn": "FS ID",
            "summarizeBy": "none"
          },
          {
            "name": "Account Categories",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8568d562-4be6-4140-a0ff-e970a3d863dc",
            "sourceColumn": "Account Categories",
            "summarizeBy": "none"
          },
          {
            "name": "Sub Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44cb7691-9609-4a53-b9f2-24a1d878a886",
            "sourceColumn": "Sub Account",
            "summarizeBy": "none"
          },
          {
            "name": "Financial Statements",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed6a4e3c-492f-4a98-9abc-5366aceab03e",
            "sourceColumn": "Financial Statements",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7c152b13-788a-4436-bd76-b16519253ffa",
        "partitions": [
          {
            "name": "TB_N",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=10L1ckm1J6DY8zyEJD0DgZ-bdC389ThnM \"),[Delimiter=\",\", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Account ID\", type text}, {\"Account Name\", type text}, {\"Balance\", Int64.Type}, {\"Balance Type\", type text}, {\"Final Balance\", Int64.Type}, {\"ACT ID\", type text}, {\"SA ID\", type text}, {\"FS ID\", type text}, {\"Account Categories\", type text}, {\"Sub Account\", type text}, {\"Financial Statements\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Alamgir Measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "21701e88fa3347c7a702516215568255"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b25b439a-f1b1-47a2-b13b-97d5a4db65ea",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "86e98f03-de43-4dc6-9af7-02dab15ea472",
        "measures": [
          {
            "name": "Total Operating Expense",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(JR_N[Net Balance]),FILTER(JR_N,JR_N[Sub Account]=\"Operating Expense\"))",
            "formatString": "0",
            "lineageTag": "5554f5c9-23d2-496b-ac82-aa818e48394f"
          },
          {
            "name": "Total Operating Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(JR_N[Dr Amount]) - SUM(JR_N[Cr Amount]),",
              "    FILTER(",
              "        ALL(JR_N[Sub Account]),",
              "        JR_N[Sub Account] IN {\"Operating Expense\"}",
              "    )",
              ")"
            ],
            "lineageTag": "4dddf623-974d-4a24-8554-e64ba2c213d3"
          },
          {
            "name": "YTD Operating Exp",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Operating Cost],",
              "    FILTER(",
              "        ALL('Calender Amlan'[Date]),",
              "        'Calender Amlan'[Date] <= MAX('Calender Amlan'[Date])",
              "    )",
              ")"
            ],
            "lineageTag": "4b7969a4-3a64-48a4-9915-19a2da356f82"
          },
          {
            "name": "PY Operating Exp",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Operating Expense],",
              "    DATEADD('Calender Amlan'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "4a3e1d5f-9f58-44e2-a7b0-e2217cb43864"
          },
          {
            "name": "OE Variance%",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Operating Expense] - [PY Operating Exp],",
              "    [PY Operating Exp]",
              ")"
            ],
            "lineageTag": "d30c22ef-3f89-4cae-9ad2-e3b58eef17f6"
          },
          {
            "name": "MoM Operating Exp",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Operating Expense],",
              "    DATEADD('Calendar'[Date], -1, MONTH)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "ef744c21-2dd6-4be2-b7ee-ffcf0443262b"
          },
          {
            "name": "YTD Profit",
            "expression": [
              "",
              "CALCULATE(",
              "    [Net Profit],",
              "    FILTER(",
              "        ALL('Calender Amlan'[Date]),",
              "        'Calender Amlan'[Date] <= MAX('Calender Amlan'[Date])",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "44e68d9a-5449-4b39-8954-c914e0734aca"
          },
          {
            "name": "PY Profit",
            "expression": [
              "",
              "CALCULATE(",
              "    [Net Profit],",
              "    DATEADD('Calender Amlan'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "415cb6d0-4234-46a4-bcf7-3adaa56e9b0c"
          },
          {
            "name": "Profit Variance%",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    [Net Profit] - [PY Profit],",
              "    [PY Profit]",
              ")"
            ],
            "lineageTag": "d62bfe98-e2bf-496b-b6f7-84ebf113b8cc"
          },
          {
            "name": "MoM Profit",
            "expression": [
              "",
              "CALCULATE(",
              "    [Net Profit],",
              "    DATEADD('Calender Amlan'[Date], -1, MONTH)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "6bfcffa2-3b14-4ba3-8e41-3d1630bc5d56"
          },
          {
            "name": "COGS",
            "expression": "[Total Expense]-[Total Operating Expense]",
            "formatString": "0",
            "lineageTag": "a650a2ba-d4e1-4192-a4bc-bc8c7ba45ec7"
          },
          {
            "name": "Gross Profit",
            "expression": "[Total Revenue] - [COGS]",
            "formatString": "0",
            "lineageTag": "52308571-315d-4280-9af2-05415a98b8e5"
          },
          {
            "name": "PM Operating Exp",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Operating Expense],",
              "    DATEADD('Calender Amlan'[Date], -1, MONTH)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "4c2d8899-ba84-45d8-a2f1-44716011ef78"
          }
        ],
        "partitions": [
          {
            "name": "Alamgir Measures",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_6e92fd0d-537d-46d8-bda8-760b71513fd5",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7d65dd00-36ae-43c3-ae2d-d615f67496d8",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "4ca321ba-f00d-4e3d-b7a8-040d98e2e49f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "0fd00c1f-a207-482c-ad76-5c2ff2c26a23",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "bdb82122-b8db-42a4-bf51-0279f28caced",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "b6f302af-d30c-4f87-ae9b-ce474e9dc613",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "427eaafa-f141-42b8-a9d8-168dd43f59ff",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "cee0e9e0-a329-439f-aced-5ef8ea70b1a8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1de18c89-34f4-438c-a335-06e83de986ed",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d402672b-ceb5-41c7-9d8c-ebe74af42063",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "4979ff9d-4d7c-4a4b-9026-6064660c2c8e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "53202c27-c897-4035-a102-51272ca0d652",
                "ordinal": 3
              }
            ],
            "lineageTag": "2a269962-7a13-4ff2-a24b-4aea5eb28f95"
          }
        ],
        "isHidden": true,
        "lineageTag": "e7f95b81-713f-45ba-ab99-9dc3e3801f98",
        "partitions": [
          {
            "name": "LocalDateTable_6e92fd0d-537d-46d8-bda8-760b71513fd5",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('JR_N'[Start of Month])), 1, 1), Date(Year(MAX('JR_N'[Start of Month])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "16ab0ee5-de04-4374-9c81-3b4c7e956ce2",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_22be8054-467e-4a80-a821-4528173dc1a7"
                },
                "isDefault": true,
                "relationship": "4b706daf-94f5-49ac-8899-a0acde9960ee"
              }
            ]
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5e39255e-ebc4-40f8-9c3e-c4cbb3583e64",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Start of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9d10f06-efc9-4e02-b8f2-72ba97a78097",
            "sourceColumn": "Start of Month",
            "summarizeBy": "none"
          },
          {
            "name": "Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e2cb5ae-d97f-4446-8fbe-78f548b4cc52",
            "sourceColumn": "Day Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "153add86-8ce0-4ef2-9414-ec3a8ec769bd",
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1v0FZwY8rncl1QWTZGffaS0OZ275GfIVM \"),[Delimiter=\",\", Columns=14, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Journal ID\", type text}, {\"Date\", Int64.Type}, {\"Account Name\", type text}, {\"Dr Amount\", Int64.Type}, {\"Cr Amount\", Int64.Type}, {\"Details\", type text}, {\"Cash flow statement operator\", type text}, {\"Cash flow Amount\", Int64.Type}, {\"ACT ID\", type text}, {\"SA ID\", type text}, {\"FS ID\", type text}, {\"Account Categories\", type text}, {\"Sub Account\", type text}, {\"Financial Statements\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",null,\"0\",Replacer.ReplaceValue,{\"Journal ID\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",null,0,Replacer.ReplaceValue,{\"Dr Amount\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",null,0,Replacer.ReplaceValue,{\"Cr Amount\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Replaced Value2\", \"Balance\", each [Cr Amount]-[Dr Amount]),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Added Custom\", \"Net Balance\", each if [Balance] < 0 then [Balance]*-1 else [Balance]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"Balance\", Int64.Type}, {\"Net Balance\", Int64.Type}, {\"Date\", type date}}),",
                "    #\"Inserted Start of Month\" = Table.AddColumn(#\"Changed Type1\", \"Start of Month\", each Date.StartOfMonth([Date]), type date),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Inserted Start of Month\",{{\"Start of Month\", type date}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type2\",{\"Date\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Duplicates\", each [Date] <> null and [Date] <> \"\"),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Filtered Rows\", \"Year\", each Date.Year([Date]), Int64.Type),",
                "    #\"Inserted Start of Month1\" = Table.AddColumn(#\"Inserted Year\", \"Start of Month\", each Date.StartOfMonth([Date]), type date),",
                "    #\"Inserted Day Name\" = Table.AddColumn(#\"Inserted Start of Month1\", \"Day Name\", each Date.DayOfWeekName([Date]), type text),",
                "    #\"Extracted First Characters\" = Table.TransformColumns(#\"Inserted Day Name\", {{\"Day Name\", each Text.Start(_, 3), type text}}),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Extracted First Characters\",{{\"Start of Month\", type text}})",
                "in",
                "    #\"Changed Type3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_22be8054-467e-4a80-a821-4528173dc1a7",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1c540487-e66f-4e48-b69d-42a5649e040e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "4e4dfbba-36b2-4e2f-9bd8-d747a8e89b1e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "bc94edd4-04a6-476e-bb3f-693b9b6e176d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1a26441a-beff-4bb3-ad7c-3d9b84b6fada",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "45b0d46b-06cd-4c0f-964b-e46c78c73a9c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a9e39c2d-07ff-4b9c-87e1-216d631d619b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "897bc405-cf3d-4304-9480-7b2140f5e6a8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "664b3011-5418-4359-bf13-6af5a8e23280",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "111b5d1c-d253-48e5-bab0-6beda64d5536",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "abe57fae-0d1a-4fc9-9604-94a82e10da84",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "0aee8841-e5ce-435d-9495-84ec6bac70da",
                "ordinal": 3
              }
            ],
            "lineageTag": "245fbfc4-e5a7-47c1-b7ea-0a81eb35f205"
          }
        ],
        "isHidden": true,
        "lineageTag": "d7ea2149-e1df-47b1-85dc-fe6c147d073c",
        "partitions": [
          {
            "name": "LocalDateTable_22be8054-467e-4a80-a821-4528173dc1a7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[Date])), 1, 1), Date(Year(MAX('Calendar'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}